import type { DecisionCampaign, DecisionResult, DecisionRunEvidence, PlannedDecisionRun } from '../twin/decision/types';
import { wholeExperimentReport } from '../twin/experiment/report';
import { resolveAsset } from '../twin/assets/design';
const format = (value: number | null | undefined, digits = 4) => value == null || !Number.isFinite(value) ? 'unavailable' : value.toLocaleString('en-US', { maximumFractionDigits: digits });
export type InspectDecisionEvidence = (run: PlannedDecisionRun, evidence: DecisionRunEvidence, context?: { assetId: string; timeS: number }) => void;

export function DecisionRunExplanation({ campaign, result, run, onInspect, disabled }: { campaign: DecisionCampaign; result: DecisionResult; run: PlannedDecisionRun; onInspect: InspectDecisionEvidence; disabled: boolean }) {
  const evidence = result.runs.find(item => item.id === run.id), report = evidence?.state ? wholeExperimentReport(evidence.state) : null;
  const evaluation = result.evaluations.find(item => item.candidateId === run.candidateId && item.sensitivityId === run.sensitivityId);
  const requirements = evaluation?.requirements.filter(item => item.scenarioId === run.scenarioId || item.scenarioId === null) ?? [];
  return <section aria-label="Selected decision run explanation" data-testid="decision-run-explanation">
    <h3>Selected scenario · whole-run evidence beside final values</h3>
    <p><code>{run.id}</code> · {run.scenarioId} / {run.sensitivityId}. Origin: {result.provenance === 'executed' ? 'executed simulated model' : 'imported supplied evidence; reproduction required'}. Execution: {evidence?.status ?? 'not executed'}. Campaign feasibility: {evaluation?.feasibility ?? 'unresolved'}.</p>
    {report?.available ? <>
      <p>Whole-run interval: evaluation 0–{format(report.metrics.elapsedS)} s; absolute simulation origin {format(report.coverage.evaluationOriginTimeS)} s; warmup {format(report.coverage.warmup.elapsedS)} s ({report.coverage.warmup.status}). Final values refer only to absolute {format(report.coverage.physicalTimeS)} s.</p>
      <table><caption>{run.id} · authoritative full-run metrics and labeled final boundary</caption><thead><tr><th>Metric</th><th>Whole run</th><th>Final boundary</th></tr></thead><tbody>
        <tr><th>Bulk coolant temperature, K</th><td>Maximum {format(report.metrics.maxCoolant?.value)} at evaluation {format(report.metrics.maxCoolant?.timeS)} s · {report.metrics.maxCoolant?.assetId ?? 'unavailable'}</td><td>{format(report.finalState.maxCoolantK)}</td></tr>
        <tr><th>Residual air temperature, K</th><td>Maximum {format(report.metrics.maxAir?.value)} at evaluation {format(report.metrics.maxAir?.timeS)} s · {report.metrics.maxAir?.assetId ?? 'unavailable'}</td><td>{format(report.finalState.maxAirK)}</td></tr>
        <tr><th>Useful accelerators</th><td>Minimum {format(report.metrics.minServiceable?.value)}; unmet {format(report.metrics.shortfallAcceleratorS)} accelerator-s</td><td>{format(report.finalState.serviceableAccelerators)} useful / {format(report.finalState.energizedAccelerators)} energized</td></tr>
        <tr><th>Service interruption, s</th><td>Total interval union {format(report.metrics.serviceViolationS)}; longest contiguous {format(report.metrics.longestInterruptionS)}</td><td>Final service alone does not erase earlier interruption.</td></tr>
        <tr><th>Recovery, evaluation s</th><td>Onset {format(report.recovery.onsetTimeS)}; confirmation {format(report.recovery.confirmationTimeS)}; status {report.recovery.status}</td><td>Continuous dwell {format(run.definition.recovery.dwellS)} s; confirmation from fault {format(report.recovery.confirmationFromEventS)} s</td></tr>
        <tr><th>Included cost, USD</th><td>{format(evaluation?.rankingCostUSD, 2)} · {campaign.objective.rankingCostBasis}</td><td>Equipment, installation and contingency assumptions</td></tr>
      </tbody></table>
      <p>Original experiment / Phase 5 verdict: <strong>{report.evaluation.outcome}</strong>. Phase 6 evaluates the declared campaign requirements: <strong>{evaluation?.feasibility ?? 'unresolved'}</strong>. A Phase 5 zero-interruption requirement can fail while Phase 6’s explicit allowed shortfall, interruption and confirmation limits pass; neither verdict rewrites the raw metrics.</p>
      <button disabled={disabled || !evidence?.state} onClick={() => onInspect(run, evidence!)}>Inspect completed run history</button><p>This explicit action saves the current project and loads this completed scenario once. Event navigation then inspects isolated history without changing its evidence.</p>
    </> : <p>Whole-run evidence unavailable. {evidence?.reason ?? 'This selected run has not completed.'}</p>}
    <details open><summary>Exact requirements, margins and supported evidence</summary>{requirements.map((requirement, index) => {
      const assetId = requirement.assetIds.find(id => resolveAsset(run.design, id));
      const timeS = requirement.timeS == null || evidence?.state?.experiment?.originTimeS == null ? null : requirement.timeS + evidence.state.experiment.originTimeS;
      return <article key={`${requirement.id}-${index}`}><p><strong>{requirement.id} · {requirement.status}</strong>: {format(requirement.actual, 8)} {requirement.operator} {format(requirement.threshold, 8)} {requirement.unit}; signed margin {format(requirement.margin, 8)}; tolerance {requirement.tolerance}. {requirement.scenarioId ?? 'installed design / cost'} / {requirement.sensitivityId}.</p><p>{requirement.reason}</p>{assetId && timeS != null && evidence?.state && requirement.scenarioId === run.scenarioId && <button disabled={disabled} onClick={() => onInspect(run, evidence, { assetId, timeS })}>Inspect {requirement.id} asset/time evidence</button>}</article>;
    })}</details>
    <p>{evaluation?.includedCost.exclusions ?? 'Included cost scope unavailable.'}</p>
  </section>;
}

export function DecisionTimeComparison({ campaign, result, scenarioId, sensitivityId }: { campaign: DecisionCampaign; result: DecisionResult; scenarioId: string; sensitivityId: string }) {
  const series = result.runs.filter(item => item.scenarioId === scenarioId && item.sensitivityId === sensitivityId && item.state?.experiment);
  const maxTime = Math.max(1, ...series.map(item => item.state!.experiment!.definition.durationS));
  const maxCapacity = Math.max(1, ...series.flatMap(item => item.state!.experiment!.metrics.trace.map(point => point.requiredAccelerators)));
  const colors = ['#a3efd9', '#d4b1ff', '#ffc67e', '#8fbaff'];
  return <section aria-label="Common time comparison" data-testid="decision-time-comparison"><h3>Compare the same declared scenario on evaluation time</h3><p>Scenario {scenarioId} / {sensitivityId}. Horizontal axis: experiment-relative seconds from each run’s evaluation origin. Points are retained canonical observations of useful accelerators; gaps are not padded and lines do not interpolate failures or switch state. Whole-run extrema and integrals are listed separately above.</p>
    <svg viewBox="0 0 680 200" aria-label="Useful accelerators on a common evaluation-relative time axis"><title>Common experiment-relative time; actual retained useful-service observations</title><path d="M30 20V165H660" stroke="#87a5ad" fill="none"/>{series.map((item, index) => <g key={item.id}>{item.state!.experiment!.metrics.trace.map(point => point.serviceableAccelerators == null ? null : <circle key={point.timeS} cx={30 + point.timeS / maxTime * 620} cy={160 - point.serviceableAccelerators / maxCapacity * 125} r={3 + index} fill="none" stroke={colors[index % colors.length]} strokeWidth="2"/>)}{item.state!.experiment!.definition.disturbances.filter(event => event.kind === 'trip' || event.kind === 'maintenance').map(event => <path key={event.id} d={`M${30 + event.timeS / maxTime * 620} 20V165`} stroke={colors[index % colors.length]} strokeDasharray="4 4" />)}</g>)}<text x="30" y="190" fill="#bad0d3">0 s</text><text x="610" y="190" fill="#bad0d3">{format(maxTime)} s</text></svg>
    <table><caption>Scenario alignment, disturbance footprint and accessible trace values</caption><thead><tr><th>Candidate / origin</th><th>Duration / warmup s</th><th>Disturbance assets and evaluation time</th><th>Observed values</th></tr></thead><tbody>{series.map((item, index) => { const run = item.state!.experiment!; return <tr key={item.id}><th><span style={{ color: colors[index % colors.length] }}>● </span>{campaign.candidates.find(candidate => candidate.id === item.candidateId)?.label ?? item.candidateId}<br/>{result.provenance} · {item.id}</th><td>{format(run.metrics.elapsedS)} observed / {format(run.definition.durationS)} requested; warmup {format(run.warmup.elapsedS)}, origin {format(run.originTimeS)}</td><td>{run.definition.disturbances.length ? run.definition.disturbances.map(event => `${event.kind} ${event.assetId} at ${event.timeS} s`).join('; ') : 'No disturbance'}</td><td><details><summary>Time s → useful accelerators / max coolant K</summary>{run.metrics.trace.map(point => <p key={point.timeS}>{format(point.timeS)} → {format(point.serviceableAccelerators)} / {format(point.maxCoolantK)}</p>)}</details></td></tr>; })}</tbody></table>
  </section>;
}
