import { useMemo, useState } from 'react';
import type { Design, SimulationState } from '../twin/types';
import type { ExperimentDefinition } from '../twin/experiment/types';
import { createExperimentDefinition, disturbanceFootprints } from '../twin/experiment/definition';
import { experimentRecoveryReport } from '../twin/experiment/report';
import { comparePair } from '../twin/experiment/runner';
const number=(value:number|null|undefined,digits=2)=>value===null||value===undefined?'unavailable':value.toLocaleString('en-US',{maximumFractionDigits:digits});
const when=(value:number|null|undefined)=>value===null||value===undefined?'none observed':`${number(value)} s`;
export function ExperimentReport({state,compact=false}:{state:SimulationState;compact?:boolean}) {
  const run=state.experiment;
  if(!run)return <p className="muted" data-testid="legacy-whole-run-unavailable">Whole-run metrics unavailable for this legacy run. Start an explicit derived experiment to recalculate its full history.</p>;
  const m=run.metrics,recovery=experimentRecoveryReport(state)!;
  return <section className="experiment-report" aria-label="Whole-run report" data-testid="whole-run-report">
    <h3>Whole-run report</h3><output data-testid="experiment-outcome"><strong>{run.status} · {run.evaluation.outcome}</strong> · {number(m.elapsedS)} / {number(run.definition.durationS)} s evaluated</output>
    <p>{run.evaluation.reasons.join(' ')||'All declared whole-run success criteria satisfied.'}</p>{(m.unavailableS>0||m.boundaryHealthy===null)&&<p role="note">Measurements unavailable over {number(m.unavailableS)} s or at the terminal boundary. Numbers below are partial observed totals; whole-window interruption and thermal conclusions are unavailable.</p>}
    <dl className="experiment-metrics">
      <div><dt>Unmet accelerator requirement</dt><dd data-testid="experiment-shortfall">{number(m.shortfallAcceleratorS)} accelerator-seconds</dd></div>
      <div><dt>Minimum serviceable capacity</dt><dd>{number(m.minServiceable?.value,0)} accelerators at {when(m.minServiceable?.timeS)}</dd></div>
      <div><dt>Maximum bulk coolant</dt><dd>{number(m.maxCoolant?.value,4)} K at {when(m.maxCoolant?.timeS)} · {m.maxCoolant?.assetId??'unavailable'}</dd></div>
      <div><dt>Maximum residual air</dt><dd>{number(m.maxAir?.value,4)} K at {when(m.maxAir?.timeS)} · {m.maxAir?.assetId??'unavailable'}</dd></div>
      <div><dt>Service violation duration</dt><dd>{number(m.serviceViolationS)} s · first {when(m.firstServiceViolationS)}</dd></div>
      <div><dt>Thermal violation duration</dt><dd>{number(m.thermalViolationS)} s · first {when(m.firstThermalViolationS)}</dd></div>
      <div><dt>Time with any violation</dt><dd>{number(m.anyViolationS)} s · campus union</dd></div>
      <div><dt>Service interruption episodes</dt><dd>{m.interruptionCount} · longest {number(m.longestInterruptionS)} s</dd></div>
      <div><dt>Sustained recovery</dt><dd data-testid="experiment-recovery">{recovery.status} · onset {when(recovery.onsetTimeS)} · confirmed {when(recovery.confirmationTimeS)}</dd></div>
      <div><dt>Recorded fault reference</dt><dd>{recovery.referenceEventId??'no recorded fault reference'} at {when(recovery.referenceEventTimeS)}; recovery onset after fault {when(recovery.onsetFromEventS)}; confirmation after fault {when(recovery.confirmationFromEventS)}</dd></div><div><dt>Qualifying violation onset</dt><dd>{when(recovery.violationOnsetTimeS)}; recovery onset after violation {when(recovery.onsetElapsedS)}; confirmation after violation {when(recovery.confirmationElapsedS)}</dd></div>
    </dl>
    {!compact&&<><p>Final state: {number(state.modules.reduce((sum,module)=>sum+module.availableAccelerators,0),0)} serviceable accelerators; {number(Math.max(...state.modules.map(module=>module.coolantK)),4)} K maximum coolant. A healthy endpoint cannot erase earlier interruption.</p><dl className="experiment-metrics">
      <div><dt>Storage discharge / charge</dt><dd>{number(m.batteryDischargeWh)} / {number(m.batteryChargeWh)} Wh at the bus</dd></div><div><dt>Storage conversion losses / net stored change</dt><dd>{number(m.batteryLossWh)} / {number(m.batteryNetChangeWh)} Wh</dd></div><div><dt>Controller transitions</dt><dd>{m.controllerTransitionCount} · {m.controllerEvidenceTruncated?'detail truncated, total retained':'bounded reason/asset evidence retained'}</dd></div><div><dt>Warmup</dt><dd>{run.warmup.status} · {number(run.warmup.elapsedS)} s excluded · evaluation origin {when(run.originTimeS)}</dd></div>
    </dl><details><summary>Recorded definition, assumptions and evidence</summary><p>Thresholds: service ≥ required minus {number(run.definition.recovery.capacityToleranceAccelerators)} accelerators; every module coolant &lt; {number(run.definition.recovery.coolantLimitK)} K and air &lt; {number(run.definition.recovery.airLimitK)} K, plus declared temperature tolerance {number(run.definition.recovery.temperatureToleranceK)} K. Recovery dwell {run.definition.recovery.dwellS} s continuously. Numerical step {run.definition.integrationStepS} s; events resolve on integer seconds.</p><p>Installed capacity, energized capacity and required service remain distinct. Workload utilization {number(run.definition.workload.utilization*100)}% does not reduce the declared required accelerator count. Accelerator-seconds are unmet requirement, without training-throughput or monetary conversion.</p><p>Detailed trace {m.trace.length}/{m.traceSamplesSeen} samples; {m.traceTruncated?'gaps present after retention, with extrema preserved':'full observed sample coverage'}. Interval evidence {m.intervalEvidenceTruncated?'truncated':'within retention'}. All aggregate durations and counts remain authoritative. Imported checkpoint summaries are supplied evidence; explicit replay recalculates them.</p><pre>{JSON.stringify({definition:run.definition,inputs:run.inputs,violations:m.intervals,controllerTransitions:m.controllerTransitions},null,2)}</pre></details></>}
  </section>;
}
export function ExperimentPanel({design,state,busy,onStart,onPrepare,onPause,onStep,onCancel}:{design:Design;state:SimulationState;busy:boolean;onStart:(definition:ExperimentDefinition)=>void;onPrepare:(definition:ExperimentDefinition)=>void;onPause:()=>void;onStep:()=>void;onCancel:()=>void}) {
  const[preset,setPreset]=useState('reference'),[mode,setMode]=useState<'cold'|'settled'>('cold'),[duration,setDuration]=useState(20),[dwell,setDwell]=useState(5),[maxWarmup,setMaxWarmup]=useState(1200),[allowedShortfall,setAllowedShortfall]=useState(0),[problem,setProblem]=useState('');
  const candidate=useMemo(()=>{try{return{definition:createExperimentDefinition(design,{name:preset==='reference'?'20 second network interruption':'Healthy reference experiment',durationS:duration,initial:{mode,settling:{maxWarmupS:maxWarmup}},recovery:{dwellS:dwell},success:{maxShortfallAcceleratorS:allowedShortfall,maxServiceViolationS:allowedShortfall>0?duration:0},disturbances:preset==='reference'?[{id:'reference-core-trip',kind:'trip',assetId:'shore/cluster-core',timeS:5},{id:'reference-core-restore',kind:'restore',assetId:'shore/cluster-core',timeS:15}]:[]}),error:''};}catch(error){return{definition:null,error:String(error)};}},[design,preset,mode,duration,dwell,maxWarmup,allowedShortfall]);
  return <section className="twin-card experiment-panel" aria-label="Whole experiment">
    <h2>Whole experiment</h2><p>Simulated, design-stage prototype. Define a bounded observation window and inspect both the final state and its complete interruption history.</p>
    <div className="experiment-fields"><label>Experiment<select aria-label="Experiment" value={preset} onChange={event=>setPreset(event.target.value)} disabled={busy}><option value="reference">20 second network interruption</option><option value="healthy">Healthy reference</option></select></label><label>Initial conditions<select aria-label="Experiment initial conditions" value={mode} onChange={event=>setMode(event.target.value as typeof mode)} disabled={busy}><option value="cold">Cold start</option><option value="settled">Settled start</option></select></label><label>Evaluation duration, s<input aria-label="Experiment duration seconds" type="number" min="0" max="86400" step="1" value={duration} onChange={event=>setDuration(Number(event.target.value))} disabled={busy}/></label><label>Recovery dwell, s<input aria-label="Recovery dwell seconds" type="number" min="0" max="86400" step="1" value={dwell} onChange={event=>setDwell(Number(event.target.value))} disabled={busy}/></label>{mode==='settled'&&<label>Maximum warmup, s<input aria-label="Maximum warmup seconds" type="number" min="30" max="86400" step="1" value={maxWarmup} onChange={event=>setMaxWarmup(Number(event.target.value))} disabled={busy}/></label>}<label>Allowed unmet requirement, accelerator-s<input aria-label="Allowed unmet accelerator seconds" type="number" min="0" value={allowedShortfall} onChange={event=>setAllowedShortfall(Number(event.target.value))} disabled={busy}/></label></div>
    <p>Required capacity {number(design.config.requestedAccelerators,0)} accelerators; installed {number(design.provisionedAccelerators,0)}. Cluster {design.config.requireClusterNetwork?'required':'optional'}; external {design.config.requireExternalNetwork?'required':'optional'}. Strict coolant &lt;318.15 K and air &lt;313.15 K across all modules; thermal violation allowance 0 s.</p>
    {mode==='settled'&&<p>Settling requires 30 continuous seconds with module temperature rates ≤0.001 K/s, storage rate ≤0.01 Wh/s, no pending or changing controllers, full service and satisfied thermal limits. Integer-second confirmation; maximum {maxWarmup} s. Warmup timeout does not start evaluation; no physical state is refilled or reset at the evaluation origin.</p>}
    {candidate.definition&&<details><summary>Disturbance footprint and experiment assumptions</summary><pre>{JSON.stringify({footprints:disturbanceFootprints(design,candidate.definition),definition:candidate.definition},null,2)}</pre></details>}
    <div className="twin-actions"><button disabled={busy||!candidate.definition} onClick={()=>onPrepare(candidate.definition!)}>Prepare experiment for stepping</button><button disabled={busy||!candidate.definition} onClick={()=>{try{setProblem('');onStart(candidate.definition!);}catch(error){setProblem(String(error));}}}>Start whole experiment</button><button disabled={!busy} onClick={onPause}>Pause experiment</button><button disabled={busy||!state.experiment||['completed','cancelled','warmup-timeout'].includes(state.experiment.status)} onClick={onStep}>Step experiment 1 s</button><button disabled={!state.experiment||['completed','cancelled','warmup-timeout'].includes(state.experiment.status)} onClick={onCancel}>Cancel experiment</button></div>
    {(problem||candidate.error)&&<p role="alert">{problem||candidate.error}</p>}<ExperimentReport state={state}/>
  </section>;
}
export function ExperimentComparison({runs}:{runs:{label:string;state:SimulationState}[]}) {
  const duration=Math.max(1,...runs.map(run=>run.state.experiment?.definition.durationS??0));
  return <section className="experiment-timeline" aria-label="Aligned experiment intervals"><h3>Aligned experiment intervals</h3><p>Evaluation time begins after the documented warmup for each run. Solid bars show retained service interruption intervals; markers show declared fault inputs. Exact totals remain in each whole-run report.</p><svg viewBox={`0 0 700 ${runs.length*55+35}`} aria-label="Service interruptions aligned by evaluation time"><title>Service interruptions and disturbance markers on a shared evaluation axis</title>{runs.map((item,index)=>{const run=item.state.experiment;return <g key={item.label}><text x="0" y={index*55+14}>{item.label}</text><line x1="0" x2="700" y1={index*55+35} y2={index*55+35} stroke="#46606a"/>{run?.metrics.intervals.filter(interval=>interval.service).map((interval,i)=><rect key={i} x={interval.startS/duration*700} y={index*55+24} width={Math.max(1,(interval.endS-interval.startS)/duration*700)} height="20" fill="#f4ad80"/>)}{run?.definition.disturbances.map(event=><line key={event.id} x1={event.timeS/duration*700} x2={event.timeS/duration*700} y1={index*55+19} y2={index*55+48} stroke={event.kind==='restore'?'#9bedd9':'#f8d599'} strokeDasharray="3 2"><title>{event.kind} {event.assetId} at {event.timeS} s</title></line>)}</g>;})}<text x="0" y={runs.length*55+20}>0 s</text><text x="700" y={runs.length*55+20} textAnchor="end">{number(duration)} s</text></svg></section>;
}
export function CounterfactualReport({faulted,baseline}:{faulted:SimulationState;baseline:SimulationState}) {
  const result=comparePair(faulted,baseline);
  return <section className="twin-card" aria-label="Faulted versus unfaulted result"><h3>Faulted versus unfaulted</h3><output data-testid="counterfactual-result">{result.status}: {result.difference?`${number(result.difference.shortfallAcceleratorS)} accelerator-seconds incremental unmet requirement (faulted minus unfaulted)` : result.reasons.join(' ')}</output><p>Each run starts from the same saved initial physical state. Only the declared fault sequence is suppressed; startup and warmup remain visible in both absolute reports.</p></section>;
}
