import { useMemo } from 'react';
import type { Design, SimulationState, Summary } from '../twin/types';
import { REFERENCE_SOURCES } from '../twin/catalog/reference';
import { constraints, marineScreen } from '../twin/analysis/reports';
const n=(x:number|null,d=2)=>x===null?'unknown':x.toLocaleString('en-US',{maximumFractionDigits:d});
export function Trend({history}:{history:Summary[]}){
  const data=history.slice(-180),minT=Math.min(290,...data.map(s=>s.maxCoolantK)),maxT=Math.max(320,...data.map(s=>s.maxCoolantK));
  return <div className="twin-trend"><div className="twin-section-line"><span>Bulk coolant · actual model samples</span><span>{n(minT-273.15,0)}–{n(maxT-273.15,0)} °C</span></div><svg viewBox="0 0 700 90" aria-label="Bulk coolant temperature trend over simulated time"><title>Bulk coolant temperature trend over simulated time</title><path d="M0 80H700 M0 40H700" stroke="#27444e" fill="none"/>{data.length>0&&<polyline fill="none" stroke="#9bedd9" strokeWidth="2" points={data.map((s,i)=>`${i*700/Math.max(data.length-1,1)},${80-(s.maxCoolantK-minT)/(maxT-minT)*70}`).join(' ')}/>}</svg><div className="twin-section-line"><span>{data[0]?.timeS??0}s</span><span>{data.at(-1)?.timeS??0}s · no interpolation of physical fields</span></div></div>;
}
export function EvidencePanel({design,state}:{design:Design,state:SimulationState}){
  const checks=useMemo(()=>constraints(design,state),[design,state]),marine=useMemo(()=>marineScreen(design),[design]);
  return <section className="twin-evidence"><h2>Evidence & limits</h2><p>Calibration/physical validation pending. Numerical verification and generated-data tests do not commission a physical facility.</p><div className="twin-readiness">{[['Design model','Reference design · assumed equipment'],['Simulation','Reduced-order · inspect residuals'],['Data integration','Generated / import / optional local SSE'],['Empirical validation','Pending compatible measured evidence'],['Commissioning','Unassessed · no physical counterpart']].map(([name,status])=><div key={name}><strong>{name}</strong><span>{status}</span></div>)}</div><div className="twin-constraints">{checks.map(c=><div className="twin-constraint" key={c.id}><span className={`twin-tag ${c.status}`}>{c.status}</span><strong>{c.id} · {c.title}</strong><p>{c.detail}</p></div>)}</div><details><summary>Mass and freeboard by platform</summary><table><thead><tr><th>Platform</th><th>Mass, t</th><th>Draft, m</th><th>Freeboard, m</th></tr></thead><tbody>{marine.map(m=><tr key={m.platformId}><td>{m.platformId}</td><td>{n(m.massKg/1000)}</td><td>{n(m.draftM)}</td><td>{n(m.freeboardM)}</td></tr>)}</tbody></table></details><details><summary>Source and assumption registry</summary>{REFERENCE_SOURCES.map(s=><article key={s.id}><span className="twin-tag">{s.evidence}</span><h3>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>:s.title}</h3><p>{s.claim}</p><p className="muted">{s.limit}</p></article>)}</details></section>;
}
export { DataPanel } from './TwinDataPanel';
