import { validateDesign } from '../persistence/design';
import { record, keys, identity, validateStructure, string } from '../persistence/structure';
import { engineeringIdentity, equipmentFor } from '../catalog/equipment';
import { SOLVER_VERSION } from '../types';
import { METRICS_VERSION } from '../experiment/types';
import { finiteNumber } from '../safety';
import { DECISION_VERSION, DECISION_LIMITS as L, DECISION_QUALIFIER, type DecisionCampaign } from './types';

function oneOf(value:unknown,allowed:readonly unknown[],field:string){if(!allowed.includes(value))throw Error(`Unsupported ${field}: ${String(value)}`);}
function unique(entries:{id:string}[],field:string){const ids=new Set<string>();for(const e of entries){string(e.id,`${field}.id`,100);if(!e.id||ids.has(e.id))throw Error(`Duplicate or empty ${field} identity: ${e.id}`);ids.add(e.id);}}
export function decisionCampaignIdentity(campaign:DecisionCampaign):string{return identity(campaign);}
export function validateDecisionCampaign(value:unknown):asserts value is DecisionCampaign {
  validateStructure(value);record(value,'campaign');keys(value,['version','id','name','fixture','qualifier','objective','requirements','candidates','scenarios','sensitivities','tolerances','versions','execution','costPolicy','exclusions','sensitivityNote'],'campaign');
  const c=value as unknown as DecisionCampaign;
  if(c.version!==DECISION_VERSION||c.qualifier!==DECISION_QUALIFIER)throw Error('Unsupported decision version or missing concept qualifier.');
  string(c.id,'campaign.id',100);string(c.name,'campaign.name',160);if(!c.id)throw Error('Campaign identity required.');
  oneOf(c.fixture,['transfer','no-benefit-bus','no-benefit-source','nominal','sizing','sensitivity'],'fixture');
  record(c.versions,'versions');if(identity(c.versions)!==identity({solver:SOLVER_VERSION,metrics:METRICS_VERSION,schema:2,decision:DECISION_VERSION}))throw Error('Unsupported model, metrics, solver or schema version.');
  record(c.objective,'objective');keys(c.objective,['mode','unit','direction','fixedWorkload','supplyCeilingW','budgetUSD','budgetBasis','rankingCostBasis','tieRule'],'objective');
  const o=c.objective;oneOf(o.mode,['minimum-included-cost','maximum-passing-workload'],'objective mode');oneOf(o.budgetBasis,['central','upper-bound'],'budget basis');oneOf(o.rankingCostBasis,['central','upper-bound'],'ranking cost basis');
  if(o.tieRule!=='within-tolerance-shared-rank-then-stable-id')throw Error('Unsupported tie rule.');
  if(o.mode==='minimum-included-cost'){if(o.unit!=='USD'||o.direction!=='ascending')throw Error('Minimum cost requires USD ascending units.');finiteNumber(o.fixedWorkload,'fixedWorkload',{min:8,max:1000000,integer:true});}
  else if(o.unit!=='accelerators'||o.direction!=='descending'||o.fixedWorkload!==null||o.supplyCeilingW===null)throw Error('Maximum workload requires accelerators descending and a supply ceiling.');
  if(o.supplyCeilingW!==null)finiteNumber(o.supplyCeilingW,'supplyCeilingW',{min:0,max:10e9});if(o.budgetUSD!==null)finiteNumber(o.budgetUSD,'budgetUSD',{min:0,max:1e13});
  record(c.requirements,'requirements');keys(c.requirements,['nominalUnmetAcceleratorS','faultUnmetAcceleratorS','totalInterruptionS','thermalViolationS','recoveryConfirmationDeadlineS','recoveryDwellS','timeOrigin'],'requirements');
  if(c.requirements.timeOrigin!=='absolute-evaluation-time')throw Error('Recovery time origin must be absolute evaluation time.');
  for(const key of ['nominalUnmetAcceleratorS','faultUnmetAcceleratorS','totalInterruptionS','thermalViolationS','recoveryConfirmationDeadlineS','recoveryDwellS'] as const)finiteNumber(c.requirements[key],`requirements.${key}`,{min:0,max:key.includes('Accelerator')?1e9:L.horizonS});
  finiteNumber(c.requirements.recoveryDwellS,'recoveryDwellS',{min:0,max:L.horizonS,integer:true});if(c.requirements.nominalUnmetAcceleratorS!==0)throw Error('Full nominal requested useful service requires zero unmet demand.');
  record(c.tolerances,'tolerances');keys(c.tolerances,['seconds','acceleratorSeconds','watts','USD','accelerators','kelvin','nearBindingFraction'],'tolerances');for(const field of ['seconds','acceleratorSeconds','watts','USD','accelerators','kelvin','nearBindingFraction'] as const)finiteNumber(c.tolerances[field],`tolerances.${field}`,{min:0,max:field==='nearBindingFraction'?0.1:field==='USD'?1:1e-4});
  record(c.execution,'execution');keys(c.execution,['concurrency','integrationStepS','traceSamples','maxModuleSteps'],'execution');oneOf(c.execution.concurrency,[1,2],'worker pool');oneOf(c.execution.integrationStepS,[1,0.5,0.25,0.125],'integration step');finiteNumber(c.execution.traceSamples,'traceSamples',{min:2,max:L.traceSamples,integer:true});finiteNumber(c.execution.maxModuleSteps,'maxModuleSteps',{min:1,max:L.moduleSteps,integer:true});
  record(c.costPolicy,'costPolicy');if(identity(c.costPolicy)!==identity({currency:'USD',equipmentScaleLower:0.7,equipmentScaleCentral:1,equipmentScaleUpper:1.5,authority:'billOfEquipment',installation:'20%-of-equipment',contingency:'25%-of-equipment-plus-installation'}))throw Error('Unsupported included cost policy or units.');
  if(!Array.isArray(c.candidates)||c.candidates.length>L.candidates)throw Error('Candidate count exceeds bounded menu.');unique(c.candidates,'candidate');const physical=new Set<string>();
  for(const d of c.candidates){record(d,'candidate');keys(d,['id','label','design','physicalIdentity','specificationIdentity','workload','topology','controllerPolicy'],'candidate');string(d.label,'candidate label',160);validateDesign(d.design);if(![2,3].includes(d.design.config.generation)||d.design.modules.length>L.modulesPerCandidate)throw Error('Unsupported candidate generation or module envelope.');if(d.workload%8||d.workload!==d.design.config.requestedAccelerators||d.workload!==d.design.provisionedAccelerators)throw Error('Candidates require exact whole-server requested and installed workloads.');if(o.mode==='minimum-included-cost'&&d.workload!==o.fixedWorkload)throw Error('Minimum-cost candidate workloads differ.');if(d.physicalIdentity!==engineeringIdentity(d.design)||d.specificationIdentity!==identity(equipmentFor(d.design)))throw Error('Resolved design/specification fingerprint mismatch.');if(physical.has(d.physicalIdentity))throw Error('Duplicate physical candidate identity.');physical.add(d.physicalIdentity);if(d.topology!==(d.design.transfer?.topology??'single-supply-radial')||d.controllerPolicy!==(d.design.transfer?`${d.design.transfer.policy}:${d.design.transfer.enabled?'enabled':'disabled'}`:'legacy-non-transferring'))throw Error('Candidate topology or controller metadata differs.');}
  const reference=c.candidates[0]?.design.config;if(reference)for(const d of c.candidates)for(const key of ['workload','idleFraction','seawaterK','foulingResistanceKPerW','pumpSpeed','requireClusterNetwork','requireExternalNetwork'] as const)if(d.design.config[key]!==reference[key])throw Error(`Candidate fairness mismatch: ${key}`);
  if(!Array.isArray(c.scenarios)||!c.scenarios.length||c.scenarios.length>L.scenarios)throw Error('A bounded nonempty scenario suite is required.');unique(c.scenarios,'scenario');
  for(const s of c.scenarios){record(s,'scenario');keys(s,['id','label','kind','durationS','disturbanceTimeS','initialMode','settling'],'scenario');string(s.label,'scenario label',160);oneOf(s.kind,['nominal','eligible-feeder','receiving-bus','common-source','thermal'],'scenario');finiteNumber(s.durationS,'scenario.durationS',{min:1,max:L.horizonS,integer:true});if(s.initialMode!=='cold'||s.settling!=='not-requested')throw Error('Only declared cold observation is supported.');const fault=!['nominal','thermal'].includes(s.kind);if(fault)finiteNumber(s.disturbanceTimeS,'disturbanceTimeS',{min:0,max:s.durationS,integer:true});else if(s.disturbanceTimeS!==null)throw Error('Unfaulted scenario cannot declare a fault time.');if(fault&&!c.scenarios.some(b=>b.kind==='nominal'&&b.durationS===s.durationS))throw Error('Each fault requires a matching declared unfaulted baseline.');}
  if(!c.scenarios.some(s=>s.kind==='nominal'))throw Error('Nominal useful-service assessment is mandatory.');
  if(!Array.isArray(c.sensitivities)||!c.sensitivities.length||c.sensitivities.length>L.sensitivities)throw Error('A bounded sensitivity suite is required.');unique(c.sensitivities,'sensitivity');if(c.sensitivities.filter(s=>s.id==='central'&&s.parameter==='central'&&s.value===null).length!==1)throw Error('One explicit central assumption is required.');
  for(const s of c.sensitivities){record(s,'sensitivity');keys(s,['id','label','parameter','value','evidence'],'sensitivity');string(s.label,'sensitivity label',160);oneOf(s.parameter,['central','idleFraction','exchangerUAWPerK','foulingResistanceKPerW','unitCostScale'],'sensitivity parameter');if(s.evidence!=='exploratory-assumption')throw Error('Sensitivity bounds are exploratory assumptions.');if(s.parameter==='central'){if(s.value!==null||s.id!=='central')throw Error('Ambiguous central assumption.');}else{const bounds={idleFraction:[0.1,0.8],exchangerUAWPerK:[10000,2e6],foulingResistanceKPerW:[0,0.0001],unitCostScale:[0.01,100]}[s.parameter];finiteNumber(s.value,'sensitivity value',{min:bounds[0],max:bounds[1]});}}
  if(c.candidates.length*c.scenarios.length*c.sensitivities.length>L.runs)throw Error('Campaign matrix exceeds run envelope.');if(!Array.isArray(c.exclusions)||!c.exclusions.length||c.exclusions.length>32)throw Error('Unassessed conditions and exclusions must remain visible.');c.exclusions.forEach(x=>string(x,'exclusion'));string(c.sensitivityNote,'sensitivity note');
}
