import type { Design, SimulationState, Constraint } from '../types';
import type { ExperimentDefinition, PhysicalCheckpoint } from '../experiment/types';
import type { billOfEquipment } from '../analysis/reports';
import type { experimentRecoveryReport } from '../experiment/report';
import type { disturbanceFootprints } from '../experiment/definition';

export const DECISION_VERSION = 'decision-campaign-1' as const;
export const DECISION_QUALIFIER = 'Simulated, design-stage prototype; physical validation pending.';
export const DECISION_LIMITS = Object.freeze({ candidates:12, scenarios:5, sensitivities:9, runs:540, modulesPerCandidate:12, horizonS:120, concurrency:2, traceSamples:160, bytes:64*1024*1024, moduleSteps:250_000 });
export type DecisionFixture = 'transfer'|'no-benefit-bus'|'no-benefit-source'|'nominal'|'sizing'|'sensitivity';
export type ObjectiveMode = 'minimum-included-cost'|'maximum-passing-workload';
export type BudgetBasis = 'central'|'upper-bound';
export interface DecisionObjective { mode:ObjectiveMode; unit:'USD'|'accelerators'; direction:'ascending'|'descending'; fixedWorkload:number|null; supplyCeilingW:number|null; budgetUSD:number|null; budgetBasis:BudgetBasis; rankingCostBasis:BudgetBasis; tieRule:'within-tolerance-shared-rank-then-stable-id'; }
export interface DecisionRequirements { nominalUnmetAcceleratorS:number; faultUnmetAcceleratorS:number; totalInterruptionS:number; thermalViolationS:number; recoveryConfirmationDeadlineS:number; recoveryDwellS:number; timeOrigin:'absolute-evaluation-time'; }
export interface DecisionCandidate { id:string; label:string; design:Design; physicalIdentity:string; specificationIdentity:string; workload:number; topology:string; controllerPolicy:string; }
export interface DecisionScenario { id:string; label:string; kind:'nominal'|'eligible-feeder'|'receiving-bus'|'common-source'|'thermal'; durationS:number; disturbanceTimeS:number|null; initialMode:'cold'; settling:'not-requested'; }
export interface DecisionSensitivity { id:string; label:string; parameter:'central'|'idleFraction'|'exchangerUAWPerK'|'foulingResistanceKPerW'|'unitCostScale'; value:number|null; evidence:'exploratory-assumption'; }
export interface DecisionCampaign { version:typeof DECISION_VERSION; id:string; name:string; fixture:DecisionFixture; qualifier:typeof DECISION_QUALIFIER; objective:DecisionObjective; requirements:DecisionRequirements; candidates:DecisionCandidate[]; scenarios:DecisionScenario[]; sensitivities:DecisionSensitivity[]; tolerances:{ seconds:number; acceleratorSeconds:number; watts:number; USD:number; accelerators:number; kelvin:number; nearBindingFraction:number }; versions:{ solver:string; metrics:string; schema:number; decision:string }; execution:{ concurrency:1|2; integrationStepS:1|0.5|0.25|0.125; traceSamples:number; maxModuleSteps:number }; costPolicy:{ currency:'USD'; equipmentScaleLower:number; equipmentScaleCentral:number; equipmentScaleUpper:number; authority:'billOfEquipment'; installation:'20%-of-equipment'; contingency:'25%-of-equipment-plus-installation' }; exclusions:string[]; sensitivityNote:string; }
export interface PlannedDecisionRun { id:string; candidateId:string; scenarioId:string; sensitivityId:string; baselineId:string|null; design:Design; definition:ExperimentDefinition; initialState:PhysicalCheckpoint; initialStateIdentity:string; footprints:ReturnType<typeof disturbanceFootprints>; }
export interface DecisionPlan { campaignIdentity:string; candidates:number; scenarios:number; sensitivities:number; totalRuns:number; sharedBaselines:number; estimatedModuleSteps:number; runs:PlannedDecisionRun[]; }
export type DecisionExecutionStatus='invalid'|'unsupported'|'numerical-failure'|'cancelled'|'resource-limited'|'incomplete'|'completed';
export interface DecisionRunEvidence { id:string; candidateId:string; scenarioId:string; sensitivityId:string; status:DecisionExecutionStatus; reason:string|null; state:SimulationState|null; peakSupply:{value:number;timeS:number;assetId:'shore/grid';samples:number}|null; hardConstraints:Constraint[]; recovery:ReturnType<typeof experimentRecoveryReport>; incrementalShortfallAcceleratorS:number|null; }
export interface RequirementEvaluation { id:string; class:'hard-model'|'operating'|'cost'; actual:number|null; unit:'accelerator-s'|'s'|'W'|'USD'|'boolean'; threshold:number; operator:'<='|'='; tolerance:number; margin:number|null; status:'violated'|'binding'|'satisfied'|'unavailable'; scenarioId:string|null; sensitivityId:string; assetIds:string[]; timeS:number|null; reason:string; }
export interface CandidateEvaluation { candidateId:string; sensitivityId:string; execution:DecisionExecutionStatus; feasibility:'feasible'|'infeasible'|'unresolved'; workload:number; includedCost:ReturnType<typeof billOfEquipment>; rankingCostUSD:number; budgetCostUSD:number; requirements:RequirementEvaluation[]; worst:{shortfallAcceleratorS:number|null;longestInterruptionS:number|null;totalInterruptionS:number|null;thermalViolationS:number|null;recoveryConfirmationS:number|null;peakSupplyW:number|null}; reasons:string[]; completedRuns:number; requiredRuns:number; }
export interface DecisionRanking { status:'recommended'|'provisional'|'no-feasible-evaluated-candidate'|'no-admissible-candidates'|'evaluation-incomplete'|'numerical-execution-failed'; sensitivityId:string; winnerIds:string[]; orderedCandidateIds:string[]; ties:string[][]; feasibleCandidateIds:string[]; unresolvedCandidateIds:string[]; scopeComplete:boolean; }
export interface DecisionResult { version:typeof DECISION_VERSION; campaignIdentity:string; provenance:'executed'|'imported-supplied-evidence'; status:'completed'|'cancelled'|'incomplete'; plan:DecisionPlan; runs:DecisionRunEvidence[]; evaluations:CandidateEvaluation[]; ranking:DecisionRanking; sensitivityRankings:DecisionRanking[]; sensitivityConclusion:string; coverage:{completed:number;planned:number;fullyEvaluatedCandidates:number}; }
export interface DecisionExport { kind:'neptune-decision-evidence'; version:typeof DECISION_VERSION; campaign:DecisionCampaign; result:DecisionResult; evidenceIdentity:string; sourceIdentity:{sourceTree:string;commit:string}; }
export type DecisionRunExecutor=(run:PlannedDecisionRun,settings:DecisionCampaign['execution'],signal?:AbortSignal)=>Promise<DecisionRunEvidence>;
export interface DecisionRunOptions { signal?:AbortSignal; onProgress?:(result:DecisionResult)=>void; executor?:DecisionRunExecutor; concurrency?:1|2; }
